# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_NPCM_BPC)		+= npcm-bpc.o
obj-$(CONFIG_NPCM_MBOX_CERBERUS) += npcm-cerberus.o
obj-$(CONFIG_WPCM450_SOC)	+= wpcm450-soc.o
obj-$(CONFIG_NPCM_SERIAL_PORT_CONTROL) += npcm-sp-ctrl.o
