# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_NPCM_MBOX_CERBERUS) += npcm-cerberus.o
obj-$(CONFIG_MTD_NPCM_TIP_FIU) += npcm_fiu_tip.o
obj-$(CONFIG_NPCM_ESPI_VWGPIO) += npcm-espi-vwgpio.o
obj-$(CONFIG_NPCM_TIP_RNG) += npcm-tip-rng.o
